/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.actions;

import data.DetalleVentaData;
import entities.Producto;
import entities.Venta;
import entities.DetalleVenta;
import gui.complements.jDialogs.JdBuscarProducto;
import gui.complements.jPanels.JpVentas;
import gui.main.Tiendita;
import gui.model.DetalleVentaModel;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jhoselyn
 */
public class ActionsVentasProductos extends javax.swing.JPanel {

    /**
     * Creates new form ActionsVentas
     */
    private JPanel frameaction;
    private JTable tableaction;
    private DetalleVentaModel dvmodel;
    private int indexFila = -1;
    private CeldaActionVentaProducto celdaAction;
    
    public ActionsVentasProductos(JPanel frame) {
        initComponents();
        this.frameaction = frame;
    }
    
    public void setCeldaEditor(CeldaActionVentaProducto celda){
        this.celdaAction = celda;
    }
    
    public void setTabla(JTable table){
        this.tableaction = table;
        dvmodel = (DetalleVentaModel) this.tableaction.getModel();
    }
    
    public void setIndexFila(int fila) {
        this.indexFila = fila;
    }
    
    public ActionsVentasProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonClassAddProduct = new gui.styles.button.ButtonClass();
        buttonClassDeleteProduct = new gui.styles.button.ButtonClass();

        setLayout(new java.awt.GridLayout(1, 0));

        buttonClassAddProduct.setBackground(new java.awt.Color(13, 71, 161));
        buttonClassAddProduct.setText("Agregar");
        buttonClassAddProduct.setColorNormal(new java.awt.Color(13, 71, 161));
        buttonClassAddProduct.setFocusable(false);
        buttonClassAddProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonClassAddProduct.setVerifyInputWhenFocusTarget(false);
        buttonClassAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassAddProductActionPerformed(evt);
            }
        });
        add(buttonClassAddProduct);

        buttonClassDeleteProduct.setBackground(new java.awt.Color(13, 71, 161));
        buttonClassDeleteProduct.setText("Delete");
        buttonClassDeleteProduct.setColorNormal(new java.awt.Color(13, 71, 161));
        buttonClassDeleteProduct.setFocusable(false);
        buttonClassDeleteProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonClassDeleteProduct.setVerifyInputWhenFocusTarget(false);
        buttonClassDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassDeleteProductActionPerformed(evt);
            }
        });
        add(buttonClassDeleteProduct);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClassAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassAddProductActionPerformed
        // TODO add your handling code here:
        System.out.println("add");
      
        if (this.tableaction.getSelectedRow() != -1) {
            this.indexFila = this.tableaction.getSelectedRow();
            System.err.println("add " + this.indexFila);
        }
        
        JpVentas venta = ((JpVentas) this.frameaction);
        Venta ventaSelected = venta.getVentaSelected();
        if (ventaSelected != null){
            JpVentas jventa = new JpVentas();
            Window parentWindow = SwingUtilities.windowForComponent(jventa);
            Frame parentFrame = null;
            if (parentWindow instanceof Tiendita) {
                parentFrame = (Tiendita)parentWindow;
            }
            JdBuscarProducto sp = new JdBuscarProducto(parentFrame, true, ventaSelected);
            sp.setVisible(true);
        }else {
        
        }
    }//GEN-LAST:event_buttonClassAddProductActionPerformed

    private void buttonClassDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassDeleteProductActionPerformed
        // TODO add your handling code here:
        System.out.println("delete");
        
    }//GEN-LAST:event_buttonClassDeleteProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.styles.button.ButtonClass buttonClassAddProduct;
    private gui.styles.button.ButtonClass buttonClassDeleteProduct;
    // End of variables declaration//GEN-END:variables
}
